### ISSUE TITLE
hubot should tag 'chatty' messages.

### ISSUE THREAD

**Issue by cscott** [cjb/codex-blackboard#193]
Hubot should tag responses as 'chatty'. The bot mute should only mute 'chatty' messages.  Ideally messages _to_ the bot should also be (retroactively) tagged chatty, if the bot responds with the chatty flag.  That way you can hide both the pug pictures _and_ all the people asking codexbot to post pug pictures.  (But don't hide messages which trigger memes, unless they are prefixed by 'bot').

Messages asking the bot for help (or which trigger bot PM responses) should also be tagged 'chatty'.

See #181

**Comment by Torgen** [comment]
Bear in mind the effect that hiding a subset of what someone says will have on followups--if the bot, or a person, says a useless thing, then a useful thing, you can't just {display:none} the useless thing, because the useful thing will be a floating followup to nothing and may appear to come from someone else. This works better with client-side followup processing, but you still have to change the query, and therefore the indexes.

**Comment by cscott** [comment]
Closed with 29ca95d1302b8b8f4396189e8548ad005c9e0a32 except for the part where "messages which trigger memes should only be hidden if prefixed by bot" ... so there's still the possibility of inadvertently triggering the bot and getting your message hidden.  I'll try to address that in a follow-up.
