### ISSUE TITLE
Add "What puzzle should I work on?" feature

### ISSUE THREAD

**Issue by shaunagm** [cjb/codex-blackboard#194]
By Friday night it was difficult to scroll through the list of puzzles and figure out what to work on.  The "hide solved puzzles" link was very useful but it would have been even better to get a list of puzzles in order of priority.  This could be generated automatically by taking into account which puzzles are in rounds with open metas and/or which puzzles have few/no people working on them, and then modified by hand if that does not accurately reflect the priority order.  This seems like it would record and make more accessible some of the useful information we get out of roundup.

(People should still be encouraged to work on whatever they find fun, but most people have times when they've finished a puzzle - or given up on it - and spend a while looking for something else to do.)

With relatively few open puzzles this year, it wasn't strictly necessary, but might be nice for years when we've got a lot of puzzles open.

CScott/cjb/anyone else - I don't know Meteor at all but I'd be happy to pair with you to try and implement this.

**Comment by cscott** [comment]
Usually "what should I work on" is handled by the status meetings.  Maybe we should link promeniently to an appropriate wiki page or google doc summarizing the last status meeting?  Would that work?

The "status" field was also intended for this purpose, but it is not really working.  See some other bugs for making status into a sortable enumeration; one of the statuses could be "high priority" or something like that.

Or maybe just being able to add an optional "star" to puzzles we'd really like solved?

The answer to "what should I work on" is usually "metas" or "puzzles that are blocking a meta".  I'm not sure that can be done automatically, since metas are more-or-less solvable with incomplete inputs (sometimes we really need all the answers, sometimes we don't).

Another thought: this might interact with the "fresh brains" (see #191).  Some stuck puzzles might especially need "fresh brains".

@shaunagm did you find the status bar on the right side useful?  That was really this year's attempt to answer this question, because you could easily see at a glance open puzzles as well as whether the corresponding meta was solved, whether they were the last open puzzle in a round, etc.

**Comment by shaunagm** [comment]
I agree that we should better record info from the status meetings.  This year all I retained is what I remembered, which was usually just a specific puzzle or two to check when meeting was done.  I like the wiki page as a quick fix, but worry it might get out of date fast.

I like the idea of the statuses having sortable enumeration, so that you could see unsolved high priority puzzles as a group, or puzzles that need fresh brains as a group, etc.  That would solve most of my reasons for making this issue, I think. 

I found the status bar very useful, especially when there were only a few puzzles open and I could use it to pop open a few puzzle windows from puzzles with unsolved metas.  But when there are lots of puzzles open, you may want more than just that single criteria for how to pick something new to work on.  You might also want to know which puzzles need more people, which puzzles need more fresh brains, and which puzzles in open metas have been specifically starred by someone as needing puzzle answers.  After all, some metas may need puzzle answers more than others.  

I think the status bar as is + sortable enumeration would be fantastic.

**Comment by cscott** [comment]
Oh, also issue #29 might solve this problem?  That's been something I've wanted to do for a while: just have a short editable text area at the top of the blackboard, that could say, "we're going on runaround at 3:15" or "we really need more fresh brains on the round 5 meta" or whatever.

**Comment by cscott** [comment]
Oh -- and preserving *too* much information from the status meeting can also be dangerous.  It often discussed "stuck puzzles" at length, and often what happens is that the people working on the stuck puzzles start by telling everyone what they "know" about the puzzle already -- which is exactly the wrong way to get unstuck.  We weren't very good about "fresh brain" protocol this year (see http://www.danielwakabayashi.com/pturnips_andy_fresh_brains.html ), but in general that's something I try (not always successfully) to enforce during status meetings.

Anyway.  That's just to say that a simple "star" or other enumerated status could potentially be *more* useful than an all-hands status meeting.

**Comment by cscott** [comment]
Maybe comment over on issue #55, which enumerates some statuses?  Do you think the "high priority" should be one of these status levels, or orthogonal to it?  Would we want to say a puzzle is both high priority *and* needs-fresh-brains?  Maybe this should be a status list?  Questions, questions -- anyway, the discussion for that is over in #55.

**Comment by shaunagm** [comment]
Sure, I'll comment over on #55 and close this.
